[build]
  command = "npm run build"
  publish = "build"
  publish_preview = "build"

[redirects]
  "/old-url" = "/new-url"

[functions]

    [functions.hello]
    external_node_modules = [
      "module-one",
      "module-two"
    ]

[build.plugins]
  [build.plugins."@netlify/nextjs"]
    
