[build]
  command = "npm run build"
  publish = "build"
  publish_preview = "public"

[redirects]
  "/old-url" = "/new-url"

[functions]
  hello = "functions/hello.js"



[build.plugins]
  [build.plugins."@netlify/nextjs"]
    
